context:
  version: "1.0.9"

package:
  name: mcreweight
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/m/mcreweight/mcreweight-${{ version }}.tar.gz
    sha256: 3c1851ee0cdb8176733ced4bf811fb93df290e5bb3901fb16c82d57ae1fa5a1c

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - apply-weights = mcreweight.scripts.apply_weights:main
      - run-reweight = mcreweight.scripts.run_reweighting:main
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.20.0
    - pandas >=1.3.0
    - matplotlib-base >=3.4.0
    - scipy >=1.8.0
    - scikit-learn >=1.2.0
    - optuna >=2.10.0
    - seaborn >=0.12.0
    - awkward-pandas >=2023.8.0
    - numexpr >=2.7.0
    - uproot !=5.6.8,>=5.0.0
    - awkward >=2.6.0
    - pyyaml >=6.0
    - onnx >=1.15.0
    - onnxruntime >=1.16.0
    - skl2onnx >=1.15.0
    - joblib >=1.3.0
    - shap >=0.44.0
    - onnxmltools >=1.12.0
    - xgboost >=1.7.0
    - hep_ml >=0.8.0
    - mplhep >=0.3.0

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - mcreweight
      pip_check: true

about:
  summary: Tools for reweighting Monte Carlo samples to match experimental data distributions
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/tfulghes/mcreweight

extra:
  recipe-maintainers:
    - tfulghes7
